config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :meme, styles: { medium: "500x500>", thumb: "200x200>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :meme, content_type: /\Aimage\/.*\z/

  def next
    self.class.where("id < ?", id).last
  end

  def previous
    self.class.where("id > ?", id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.reverse_order
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to :root
    else
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :meme)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def previous_button(post)
    if post.previous
      link_to "Previous Post", post_path(post.previous), class: "pagination-button previous"
    end
  end
  def next_button(post)
    if post.next
      link_to "Next Post", post_path(post.next), class: "pagination-button next"
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted">Powered by SAITC &copy2018</span>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">NineG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse navbar-right" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Upload", new_post_path, :class=>"nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NineGClone</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <!-- Begin page content -->
    <main role="main" class="container">
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="post-wrapper">
  <div class="post-card">
    <h3 class="post-title"><%= link_to post.title, post_path(post), class: "post-title-link" %></h3>
    <%= image_tag(post.meme, :class => "post-image") %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <% @posts.each do |post| %>
    <%= render post %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1 class="new-post-title">New Post</h1>

<div class="new-post-form-wrapper">
  <%= form_for @post, url: posts_path, html: { multipart: true } do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control" %>

      <%= f.label :meme %>
      <%= f.file_field :meme, :class => "form-control-file" %>

      <%= f.submit :class=>"btn btn-large btn-primary"%>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<div class="main-post-wrapper">
  <div class="row pagination-row">
    <div class="col-sm-6">
      <%= previous_button(@post) %>
    </div>
    <div class="col-sm-6">
      <%= next_button(@post) %>
    </div>
  </div>
  <div class="main-post">
    <%= image_tag @post.meme, :class=>"main-post-image" %>
  </div>
</div>